# Pytorch 101 - Tensors

Pytorch is a python package targeted for mainly two uses

- A replacement for NumPy to use your GPU thus accelerating computing
- Dee learning development platform

The first concept we need to make sure we understand is the concept of a tensor.  

If you are familiar with NumPy then you are a lucky cookie.  
Tensors are similar to NumPy's ndarrays with the brilliant characteristic of being capable to use GPU to accelerate computing. 

In [2]:
# Lets import
import torch

We can create: 
- Empty tensors
- Random
- Filled with 0's
- Filled with 1's
- Directly from data
- From another tensor

And some other tricks that we'll cover later

In [17]:
# Empty
x = torch.empty(5,3)
print(x)

tensor([[ 5.9294e+00,  4.5808e-41,  5.9294e+00],
        [ 4.5808e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -1.1312e-36],
        [ 3.0915e-41,  2.0319e-43,  0.0000e+00],
        [-1.1344e-36,  3.0915e-41,  5.9293e+00]])


In [18]:
# Random
x = torch.rand(5,3)
print(x)

tensor([[0.0549, 0.3294, 0.1466],
        [0.4971, 0.2633, 0.1515],
        [0.4355, 0.9915, 0.0374],
        [0.8308, 0.4187, 0.0894],
        [0.2701, 0.6461, 0.8348]])


In [19]:
# 0's but type long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [20]:
# 1's but type int
x = torch.ones(5, 3, dtype=torch.int)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [21]:
# Directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [22]:
# We can also create tensors from other tensors and change the dtype on the new ones
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

# And of course we can get the size of a sensor
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8837, -1.9384,  0.0824],
        [ 0.5409, -1.2753,  1.2485],
        [ 1.0305, -2.1184,  0.5200],
        [-0.9521,  0.8252,  1.6442],
        [ 0.2127,  1.5367, -1.3651]])
torch.Size([5, 3])


##  Operations

It's obviously imposible to cover all operations but for the sake of giving some sort of example let keep going ;)

In [27]:
# Addition using "+" operator
x = torch.ones(5, 3)
y = torch.rand(5, 3)

print(x)
print(y)
print(x + y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4207, 0.9760, 0.3910],
        [0.2187, 0.1812, 0.1678],
        [0.1113, 0.9096, 0.2253],
        [0.8655, 0.1390, 0.5084],
        [0.2376, 0.6938, 0.3795]])
tensor([[1.4207, 1.9760, 1.3910],
        [1.2187, 1.1812, 1.1678],
        [1.1113, 1.9096, 1.2253],
        [1.8655, 1.1390, 1.5084],
        [1.2376, 1.6938, 1.3795]])


In [24]:
# Or use a function
print(torch.add(x, y))

tensor([[1.3145, 1.4350, 1.0026],
        [1.3657, 1.7708, 1.2255],
        [1.5436, 1.6044, 1.2447],
        [1.1253, 1.5685, 1.0296],
        [1.9169, 1.5857, 1.6694]])


In [26]:
# Or output to a tensor
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3145, 1.4350, 1.0026],
        [1.3657, 1.7708, 1.2255],
        [1.5436, 1.6044, 1.2447],
        [1.1253, 1.5685, 1.0296],
        [1.9169, 1.5857, 1.6694]])


In [28]:
# Or in-place
y.add_(x)
print(y)

tensor([[1.4207, 1.9760, 1.3910],
        [1.2187, 1.1812, 1.1678],
        [1.1113, 1.9096, 1.2253],
        [1.8655, 1.1390, 1.5084],
        [1.2376, 1.6938, 1.3795]])


### Indexing

All indexing in a tensor works like NumPy

In [29]:
print(x[:, 1])

tensor([1., 1., 1., 1., 1.])


### Resizing/Reshape

To reshape/resize tensors the function to use is `.view()`

In [31]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


For one element tensors the best way to obtain such is by the `.item()`

In [33]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.2545])
-1.2545496225357056


## Numpy bridge

Remember when I said tensors are NumPy ndarrays were very similar?  
Well, converting between these two is super easy here

### Tensor to NumPy

In [34]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy and Tensors will share the same space in memory as long as the tensors are located on 'CPU' (more on this later)

In [38]:
# Addition in place
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


### NumPy to Tensor

Same way, when converting an `ndarray` to `Tensor it will use CPU memory

In [39]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

Now, the moment you've all been waiting for *drum rolls**  
  
  We've talked so far on how ndaarrays and Tensors are similar and interchangable and the question why do we need tensors should arise.  
  
  Well, because we can move Tensors to GPU memory, how do we do this? With the `.to()` method.

In [41]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

**NOTE:** The previous code will not run unless you have properly configurated your GPU and CUDA.  

This is a whole different beast and it's interesting in its own but it will not be covered in here for now.